services:
  tugas_individu_db:
    image: postgres:17.5-alpine
    ports:
      - '35001:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=tugas_individu
      - POSTGRES_PASSWORD=CLI-825.2025X
      - POSTGRES_DB=tugas_individu
    volumes:
      - tugas_individu_db:/var/lib/postgresql/data

volumes:
  tugas_individu_db:
    driver: local