services:
  flight_dev_db:
    image: postgres:17.5-alpine
    ports:
      - '35001:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=flight-dev
      - POSTGRES_PASSWORD=CLI-825.2025X
      - POSTGRES_DB=flight-dev
    volumes:
      - flight_dev_db:/var/lib/postgresql/data

volumes:
  flight_dev_db:
    driver: local