spring:
  application:
    name: ti-2306240080

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  profiles:
    active: 'dev'

  jpa:
    hibernate:
      ddl-auto: create-drop

external:
  sidating-app-be-url: http://your-external-service-host:8080/api/v1